In [8]:
import pandas as pd

df = pd.read_excel(r"D:\OC\sales order list 20260815.xlsx")
# df = pd.read_excel(r"D:\OC\sales order list.xlsx")
df.shape

(9306, 21)

In [9]:
df["sales_order_no"].nunique()

1724

In [ ]:
df["sales_order_no"].nunique()
df.groupby("sales_order_no").size()
df.isna().sum()

In [10]:
item_totals = (
    df.groupby("sales_order_no")["amount"]
      .sum()
)

item_discount_totals= (
    df.groupby("sales_order_no")["discount"]
      .sum()
)
subtotals = (
    df.groupby("sales_order_no")["subtotal_amount"]
      .first()
)

check = pd.DataFrame({
    "item_total": item_totals,
    "item_discount_total":item_discount_totals,
    "subtotal": subtotals
})

check["difference"] = (
    check["subtotal"] - (check["item_total"]+check["item_discount_total"])
)

check

                item_total  item_discount_total    subtotal  difference
sales_order_no
2014-864061        7500.00                  0.0     7500.00         0.0
2014-864069      453223.00                  0.0   453223.00         0.0
2014-864105     1094975.42                  0.0  1094975.42         0.0
2014-864136       32200.00                  0.0    32200.00         0.0
2014-864143        5439.00                  0.0     5439.00         0.0
...                    ...                  ...         ...         ...
2026-864111        4795.00               -450.0     4345.00         0.0
2026-864115       14420.00                  0.0    14420.00         0.0
2026-864117        2600.00                  0.0     2600.00         0.0
2026-864118         745.00               -225.0      520.00         0.0
2026-864120       36891.00                  0.0    36891.00         0.0

[1724 rows x 4 columns]

In [13]:
check[check["difference"].abs() > 0.01]

                item_total  item_discount_total    subtotal  difference
sales_order_no
2015-864154       71910.00                 0.00    74815.20     2905.20
2019-864199     1651814.10            -27637.08  1688002.02    63825.00
2020-864270       27175.00              -774.75    25050.25    -1350.00
2021-864272     3097376.00                 0.00  1548688.00 -1548688.00
2021-864340      398922.28            -17344.76   205109.50  -176468.02
2021-864361      157720.00                 0.00    78860.00   -78860.00
2022-864153       27000.00            -14100.00    13500.00      600.00
2022-864154       27000.00            -14100.00    13500.00      600.00
2022-864238      566000.00                 0.00   283000.00  -283000.00
2022-864262       30328.00              -900.00    14714.00   -14714.00
2022-864301       39006.00              -900.00    20403.00   -17703.00
2023-864083       91858.00             -2400.00    55529.00   -33929.00
2023-864222     1360172.00                 0.00   680086.00  -680086.00
2023-864297        5100.00              -825.00     1450.00    -2825.00
2024-864004      123700.00              -900.00    61400.00   -61400.00
2024-864171       68996.00             -2000.00    64023.00    -2973.00
2024-864189       70224.00             -1553.80    58184.10   -10486.10
2024-864197       90440.00                 0.00    45220.00   -45220.00
2024-864209       94960.00             -6276.80    44341.60   -44341.60
2025-864165       91203.00              -450.00    47963.00   -42790.00
2025-864270       45000.00                 0.00    22500.00   -22500.00
2025-864273       80036.00                 0.00    39018.00   -41018.00
2026-864003       44550.00             -3850.00    29205.00   -11495.00
2026-864031       37495.00                 0.00    20830.00   -16665.00
2026-864045       37900.00                 0.00    18400.00   -19500.00
2026-864078       84011.80                 0.00    42135.90   -41875.90

In [12]:
check[check["difference"].abs() > 0.01].head(20)

                item_total  item_discount_total    subtotal  difference
sales_order_no
2015-864154       71910.00                 0.00    74815.20     2905.20
2019-864199     1651814.10            -27637.08  1688002.02    63825.00
2020-864270       27175.00              -774.75    25050.25    -1350.00
2021-864272     3097376.00                 0.00  1548688.00 -1548688.00
2021-864340      398922.28            -17344.76   205109.50  -176468.02
2021-864361      157720.00                 0.00    78860.00   -78860.00
2022-864153       27000.00            -14100.00    13500.00      600.00
2022-864154       27000.00            -14100.00    13500.00      600.00
2022-864238      566000.00                 0.00   283000.00  -283000.00
2022-864262       30328.00              -900.00    14714.00   -14714.00
2022-864301       39006.00              -900.00    20403.00   -17703.00
2023-864083       91858.00             -2400.00    55529.00   -33929.00
2023-864222     1360172.00                 0.00   680086.00  -680086.00
2023-864297        5100.00              -825.00     1450.00    -2825.00
2024-864004      123700.00              -900.00    61400.00   -61400.00
2024-864171       68996.00             -2000.00    64023.00    -2973.00
2024-864189       70224.00             -1553.80    58184.10   -10486.10
2024-864197       90440.00                 0.00    45220.00   -45220.00
2024-864209       94960.00             -6276.80    44341.60   -44341.60
2025-864165       91203.00              -450.00    47963.00   -42790.00

In [ ]:

def check_group(line,grp):
    
    if grp:
        print("group")
    else:
        print("Item")
    
line=["2","3"]
group=False
it=check_group(line,group)